/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   etools-dropdown-multi.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

import {Debouncer} from '@polymer/polymer/lib/utils/debounce.js';

import {CommonFunctionality} from './mixins/common-mixin.js';

import {MissingOptions} from './mixins/missing-options-mixin.js';

import {timeOut} from '@polymer/polymer/lib/utils/async.js';

declare function MultiDropdownRequiredMixins<T extends new (...args: any[]) => {}>(base: T): T & MultiDropdownRequiredMixinsConstructor;

interface MultiDropdownRequiredMixinsConstructor {
  new(...args: any[]): MultiDropdownRequiredMixins;
}

export {MultiDropdownRequiredMixinsConstructor};

interface MultiDropdownRequiredMixins {
}

/**
 * `etools-dropdown-multi`
 */
declare class EtoolsDropdownMulti extends
  MultiDropdownRequiredMixins(
  MultiDropdownRequiredMixins) {

  /**
   * Dropdown selected values
   */
  selectedValues: any[]|null|undefined;

  /**
   * Selected options objects
   */
  selectedItems: any[]|null|undefined;

  /**
   * Array of not found values (in options list)
   */
  notFoundOptions: any[]|null|undefined;

  /**
   * Element title attribute
   */
  readonly title: string|null|undefined;
  connectedCallback(): void;
  _selectedValuesOrOptionsChanged(selectedValuesOrLength: any, options: any): void;

  /**
   * Can't use paper-listbox's on-selected-items-changed event ,
   * because paper-lisbox doesn't cover the case when selectedItems are not in the shownOptions values
   */
  _setSelectedItems(selectedValues: any[]|null): void;
  _selectedItemsChanged(selectedItems: any): void;
  _fireChangeEvent(): void;
  _setAnyNotFoundOptions(selectedItems: any, selectedValues: any): void;
  _removeSelectedItem(e: any): void;

  /**
   * This observer makes sure request for missing option is triggered only after the url is set also.
   * notFoundOption is actually this.selected
   */
  _notFoundOptionsAndUrlChanged(notFoundOptions: any, url: any): void;
  _handleSelectedNotFoundInOptions(notFoundSelectedValues: any): void;
  _onDropdownClose(): void;

  /**
   * Validate multi selection
   */
  validate(selectedValues: any): boolean;
  _getValuesFromItems(selectedItems: any): any;
  _noSelectedValues(selectedValues: any): any;
  _noSelectedItems(selectedItems: any): any;
  _selectedValuesToString(): void;
  _getElementTitle(selectedItems: any): any;
}

declare global {

  interface HTMLElementTagNameMap {
    "etools-dropdown-multi": EtoolsDropdownMulti;
  }
}
