/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   elements/searchbox-input.js
 */


// tslint:disable:variable-name Describing an API that's defined elsewhere.

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

declare class EsmmSearchboxInput extends PolymerElement {

  /**
   * Search string property
   */
  search: string|null|undefined;
}

declare global {

  interface HTMLElementTagNameMap {
    "esmm-searchbox-input": EsmmSearchboxInput;
  }
}
