/**
 * DO NOT EDIT
 *
 * This file was automatically generated by
 *   https://github.com/Polymer/tools/tree/master/packages/gen-typescript-declarations
 *
 * To modify these typings, edit the source file(s):
 *   elements/selected-options.js
 */

// tslint:disable:variable-name Describing an API that's defined elsewhere.
// tslint:disable:no-any describes the API as best we are able today

import {PolymerElement, html} from '@polymer/polymer/polymer-element.js';

import {ListItemUtils} from '../mixins/list-item-utils-mixin.js';

declare class EsmmSelectedOptions extends EsmmMixins.ListItemUtils(Object) {
  selectedItems: any[] | null | undefined;
  label: string | null | undefined;
  noLabelFloat: boolean | null | undefined;
  alwaysFloatLabel: boolean | null | undefined;
  placeholder: string | null | undefined;
  autoValidate: boolean | null | undefined;
  readonly: boolean | null | undefined;
  disabled: boolean | null | undefined;
  invalid: boolean | null | undefined;
  errorMessage: string | null | undefined;
  _hidePlaceholder: boolean | null | undefined;
  _stopEvent(e: any): void;
}

declare global {
  interface HTMLElementTagNameMap {
    'esmm-selected-options': EsmmSelectedOptions;
  }
}
